'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {root}=require('../tests/harness.cjs'),{mean,summary,acceptance,write,fileHash}=require('./evaluate-v117.cjs');
const load=f=>JSON.parse(fs.readFileSync(path.join(root,'docs/'+f+'.json'))),n=x=>Number(x).toLocaleString('en-US',{maximumFractionDigits:2}),pc=x=>(x*100).toFixed(2)+'%';
const table=(heads,rows)=>['| '+heads.join(' | ')+' |','| '+heads.map(()=> '---').join(' | ')+' |',...rows.map(r=>'| '+r.join(' | ')+' |')].join('\n');
const metricTable=(rows,vs)=>table(['策略','局数 / 独立起点','新增均值','新增中位数','较差25%均值','早死<1000','终局分数均值','16384 / 32768'],vs.map(v=>{const s=summary(rows.filter(r=>r.variant===v));return [v,`${s.games} / ${s.uniqueStarts}`,n(s.meanAdditionalMoves),n(s.medianAdditionalMoves),n(s.bottomQuartileMean),`${s.earlyDeaths}/${s.games}`,n(s.meanScore),`${s.reached16384}/${s.games} · ${s.reached32768}/${s.games}`];}));
function paired(rows,a,b){let win=0,loss=0,tie=0;for(const r of rows.filter(r=>r.variant===a)){const s=rows.find(x=>x.variant===b&&x.checkpoint===r.checkpoint&&x.repeat===r.repeat);assert.ok(s);const d=r.additionalMoves-s.additionalMoves;if(d>0)win++;else if(d<0)loss++;else tie++;}return {win,loss,tie};}
function clustersCI(rows,a,b){
 const ids=[...new Set(rows.filter(r=>r.variant===a).map(r=>r.checkpoint))],pairs=ids.map(id=>[mean(rows.filter(r=>r.variant===a&&r.checkpoint===id).map(r=>r.additionalMoves)),mean(rows.filter(r=>r.variant===b&&r.checkpoint===id).map(r=>r.additionalMoves))]);
 let state=117;const ratios=[];for(let k=0;k<10000;k++){let x=0,y=0;for(let i=0;i<pairs.length;i++){state=(Math.imul(state,1664525)+1013904223)>>>0;const p=pairs[Math.floor(state/4294967296*pairs.length)];x+=p[0];y+=p[1];}ratios.push(x/y);}ratios.sort((x,y)=>x-y);return {unit:'checkpoint cluster, average all repetitions; descriptive 10000 fixed-seed bootstrap, not an added acceptance gate',lower:ratios[249],upper:ratios[9749]};
}
function repeatedTable(rows,vs){const ids=[...new Set(rows.map(r=>r.checkpoint))];return table(['起点',...vs],ids.map(id=>[id,...vs.map(v=>rows.filter(r=>r.checkpoint===id&&r.variant===v).sort((a,b)=>a.repeat-b.repeat).map(r=>`r${r.repeat}: ${r.additionalMoves}/${r.score}/${r.maxTile}`).join('<br>')||'—')]));}
(async()=>{
 const dev=load('V11_7_DEVELOPMENT'),val=load('V11_7_VALIDATION'),other=load('V11_7_OTHER_MODES'),release=load('V11_7_RELEASE'),lat=load('V11_7_LATENCY'),replay=load('V11_7_REPLAY'),tests=load('TEST_RESULTS_V11_7'),freeze=load('V11_7_FREEZE'),diff=load('V11_7_FIRST_DIVERGENCES');
 for(const j of [dev,val,other,release,lat])assert.equal(j.complete,true);assert.ok(replay.passed&&tests.passed);const gate=acceptance(val.rows);assert.deepEqual(gate,val.acceptance);const decision=load('V11_7_RELEASE_DECISION');assert.equal(decision.gatePassed,gate.passed);
 const candidate=freeze.candidate,merge=load('V11_7_MERGE_ABLATION'),retain5=load('V11_7_RETAIN5_ABLATION');assert.ok(merge.complete&&retain5.complete);
 const otherN=new Set(other.rows.map(r=>r.checkpoint)).size;require('node:child_process').execFileSync(process.execPath,['tools/inspect-corpus-v117.cjs'],{cwd:root});const diversity=load('V11_7_CORPUS_DIVERSITY');
 const corpus=JSON.parse(fs.readFileSync(root+'/tests/fixtures/late-game-v117/manifest.json'));
 const stats=Object.fromEntries(['stable','v116',candidate].map(v=>[v,summary(val.rows.filter(r=>r.variant===v))])),godPairs={stable:paired(val.rows,candidate,'stable'),v116:paired(val.rows,candidate,'v116')};
 const result={date:new Date().toISOString(),currentHTMLSHA256:fileHash('2048-ai.html'),freeze,releaseDecision:decision,defaultPolicyDecision:load('V11_7_DEFAULT_POLICY_DECISION'),finalBuildIdentity:load('V11_7_FINAL_BUILD_IDENTITY'),releaseIdentity:load('V11_7_RELEASE_IDENTITY'),goalMet:gate.passed,protocol:load('V11_7_PROTOCOL'),validation:{uniqueStarts:20,records:val.rows.length,repeats:2,stats,pairs:godPairs,acceptance:gate,bootstrapMeanRatioAgainstStable:clustersCI(val.rows,candidate,'stable'),bootstrapMeanRatioAgainstV116:clustersCI(val.rows,candidate,'v116')},development:dev.summary,mergeAblation:merge.summary,postValidationDevelopment:{protocol:load('V11_7_RETAIN5_PROTOCOL'),results:retain5.summary,decision:load('V11_7_RETAIN5_DECISION')},otherModes:other.summary,latency:lat.summary,release:release.summary,replay:{games:replay.records,moves:replay.moves,passed:replay.passed},tests};
 write(root+'/docs/V11_7_SUMMARY.json',result);
 const lines=['# 2048 AI V11.7 实测升级报告','',
 gate.passed?`默认神级采用通过全部预定门槛的 ${candidate} 候选。`:'**没有候选通过独立验收，神级高分存活全面升级的目标尚未达成。最终神级维持输入 V11.6 的原策略；所有本轮新增规则均撤回。** 这是带完整复测证据的维护版，不能称作神级全面变强。','',
 '本报告数字均来自环境恢复后实际运行、随包保存的原始记录。重启前未保留的成绩排除；V11.6 历史报告仅用于提出问题。不会承诺每一局分数更高。','',
 '## 改动及因果依据','',
 '正常 God 的 profile 实际是 extreme，原有合并门槛 0.0005；部分标注 god 的旧分支并未生效。V11.6 额外的实际出招复核失败后回退完整 d4，改变合并后的方向，并可能将风险 verifier 从 d6 改成 d5。候选仅在原 policy-only 检查失败时，要求 d4/d6 原始推荐与合并之后推荐均一致才回退，否则保留稳定基线的完整 d5。所有合法根仍同深度完成。候选未确认的证据不会显示为共识或独立验证通过。','',
 '此处双共识实验是开发候选，不是最终冻结的 rawNoMerge；两者分别列出。终局底值平局补救独立开关测试。另测按 d5/d6 实际推荐一致采用 d6、及其与补救组合；不改权重或扩大 TT。开发阶段的完整消融表保留收益和损失，未因某局最高分选策略。','',
 metricTable([...dev.rows,...merge.rows],['stable','v116','rescue','promotion','combined','fallback','fallbackRescue','rawNoMerge']),'',
 repeatedTable([...dev.rows,...merge.rows],['stable','v116','rescue','promotion','combined','fallback','fallbackRescue','rawNoMerge']),'',
 '表格每项为新增步数 / 终局分数 / 最大方块。全部 8 个旧起点都是开发样本，过去的 holdout 标签不再代表独立验证。双共识局部修复并未恢复整条路径。更深、更多共识或改成生存概率决策都不能预设更强。','',
 '## 验证失败后的追加消融','',
 'rawNoMerge 独立验证失败后，另用旧8份开发起点检验 retain5Promotion：保留 d5/d6 实际推荐共识条件，但采用完整 d5 分数和相应 verifier 深度。它与此前 promotion 采用 d6 的实验配对，隔离共识触发与评分/复核深度的影响。仅用于开发筛选；既有20份验证局面没有被再次当成这个候选的独立验证。默认源码没有启用这项规则。','',
 metricTable([...dev.rows,...retain5.rows],['stable','v116','promotion','retain5Promotion']),'',
 repeatedTable([...dev.rows,...retain5.rows],['stable','v116','promotion','retain5Promotion']),'',
 `追加实验结论：${load('V11_7_RETAIN5_DECISION').reason}`,'',
 '## 四个退步起点及后续危险','',
 table(['起点','首次不同（从起点0计）','当时分数','稳定方向/深度','V11.6方向/深度','双共识实验方向/深度','V11.6 后128步最少空格/单合法方向状态'],diff.rows.filter(r=>['seed-2','seed-4','seed-5','seed-103'].includes(r.checkpoint)).map(r=>[r.checkpoint,r.firstDifference,r.game.score,`${r.responses.stable.best}/${r.responses.stable.depth}`,`${r.responses.v116.best}/${r.responses.v116.depth}`,`${r.responses.fallback.best}/${r.responses.fallback.depth}`,`${r.v116.next128.minEmpties}/${r.v116.next128.singleLegalStates}`])),'',
 '第一分歧原棋盘、分数、总步数、PRNG、d4/d5/d6 各根分数、原始/实际推荐、脆弱性和风险结果，以及双方后32/128步与终局尾部，见 `V11_7_FIRST_DIVERGENCES.json`。完整后续逐步日志可以重放。首次改变只是可定位机制，不能据此把整局失败完全归因于单步。','',
 '## 独立终局验证与预定门槛','','64局已知开发终局后，最终冻结 rawNoMerge：只关闭稳定策略的合并偏好，不改变主搜索评分、深度、合法根或风险预算。它对稳定基线6胜2负、均值/中位数/尾部改善，但对V11.6神级均值仍下降，seed-4/103有严重退步。双共识回退与更深实际共识未通过开发稳定性检查，保留撤回证据。候选选择在新起点终局测试前完成，没有利用新20局的胜负修改策略。最终验收门槛对两个基线完全不变。','',
 `在策略冻结之后，用从未参与本轮调参的 seeds ${corpus.protocol.seedFirst}–${corpus.protocol.seedLast} 顺序生成；保留 ${corpus.rejected.length} 个未达到目标/不合条件的局。先取16个达到17万分、再取4个达到23万分的真实非终局起点。每份记录棋盘、分数、累计步数、出生质量/势能、完整 Mulberry32 状态和来源/出招散列。覆盖 ${[...new Set(corpus.checkpoints.map(s=>s.game.board.filter(v=>!v).length))].sort((a,b)=>a-b).join('/')} 空格及 ${[...new Set(corpus.checkpoints.map(s=>Math.max(...s.game.board)))].sort((a,b)=>a-b).join('/')} 最大块。拒绝按候选胜负挑选起点。`,'',
 '每局恢复同一棋盘与同一随机流，直到无合法动作；每策略每起点重复两次，全部保留。20个独立起点不写成40个独立样本。两次重复均纳入汇总，以起点为簇补充描述性 bootstrap。冻结的rawNoMerge及其验收门槛在测试后没有修改；这20份起点此后对任何新候选都属于已知样本。后续retain5仅做旧8起点开发消融，未冒称新的独立验收。','',
 '默认候选必须同时对稳定基线与 V11.6：新增步数均值至少+5%，中位数和较差25%均值至少98%，早死比例不得增加，平均最终分数与16384/32768达到比例不得下降。早死预先定义为新增步数<1000，较差25%为最差 ceil(n/4) 局的均值。门槛在生成/测试前写入 `V11_7_PROTOCOL.json`，全部必须通过。','',
 table(['空格数','起点数'],Object.entries(diversity.summary.empties)),'',table(['几何风险分类','起点数'],Object.entries(diversity.summary.geometryClass)),'','完整出生格×2/4枚举的后继合法方向最小值与概率见 V11_7_CORPUS_DIVERSITY.json；这是棋形描述，不能等同于有限视野 survival 概率。','',metricTable(val.rows,['stable','v116',candidate]),'',
 table(['对照','均值比','中位数比','较差25%比','早死检查','分数/16384/32768检查','全部通过'],Object.entries(gate.against).map(([v,a])=>[v,a.ratios.mean.toFixed(4),a.ratios.median.toFixed(4),a.ratios.lowerQuartile.toFixed(4),String(a.checks.earlyDeath),`${a.checks.score}/${a.checks.tile16384}/${a.checks.tile32768}`,String(a.passed)])),'',
 repeatedTable(val.rows,['stable','v116',candidate]),'',
 `候选配对新增步数胜/负/平：对稳定 ${godPairs.stable.win}/${godPairs.stable.loss}/${godPairs.stable.tie}；对 V11.6 ${godPairs.v116.win}/${godPairs.v116.loss}/${godPairs.v116.tie}。均值比的起点簇 bootstrap 95%区间分别为 ${result.validation.bootstrapMeanRatioAgainstStable.lower.toFixed(3)}–${result.validation.bootstrapMeanRatioAgainstStable.upper.toFixed(3)} 和 ${result.validation.bootstrapMeanRatioAgainstV116.lower.toFixed(3)}–${result.validation.bootstrapMeanRatioAgainstV116.upper.toFixed(3)}，用于显示不确定性，不改变验收标准。`,'',
 '有限样本不能证明普遍不退步。所有退步局仍公开，最终默认版本另从这20份起点实际运行一次，见 `V11_7_RELEASE.json`；它用于核对发布策略，没有再作为新独立集合。','',
 '### 最终默认策略的实际局限','',
 metricTable(release.rows,['release']),'',
 `最终20局与V11.6神级r0的完整轨迹核对：终局一致 ${result.releaseIdentity.allSameOutcomes}，每步出招/出生/随机状态一致 ${result.releaseIdentity.allSameMovesAndBirths}，全部根评分/完成深度一致 ${result.releaseIdentity.allSameScoresAndDepths}；逐局见 V11_7_RELEASE_IDENTITY.json。这是发布一致性证据，不是新增棋力收益。`,'',
 repeatedTable(release.rows,['release']),'',
 `稳定基线与 V11.6 神级在新20起点上均实际各跑两遍：稳定基线新增均值 ${n(stats.stable.meanAdditionalMoves)}、中位数 ${n(stats.stable.medianAdditionalMoves)}、较差25%均值 ${n(stats.stable.bottomQuartileMean)}、早死 ${pc(stats.stable.earlyDeathRate)}；V11.6 对应为 ${n(stats.v116.meanAdditionalMoves)}、${n(stats.v116.medianAdditionalMoves)}、${n(stats.v116.bottomQuartileMean)}、${pc(stats.v116.earlyDeathRate)}。原协议预设的稳定基线回退在本集合上均值、较差25%和早死均更差，不能把“稳定”名称当作不退步的实测结论。最终撤销这项尚未发布的回退，维持用户附件的原神级策略。这个默认处理偏离原先的回退预案，已单独公开在 V11_7_DEFAULT_POLICY_DECISION.json；候选、验收门槛、原始数据没有更改，也没有用这些结果调出新规则或声称新默认变强。`,'',
 '## 其他模式：同名比较与重复测量','',
 `轻快、深入、极致与 V11.6 同名模式直接配对。按测试前预定的4份不同棋形旧高分起点，每份重复3次（准确源码冻结为v117-validation.html；最终默认仅改回God选项，三个同名模式完整后续代码及混合棋盘配置逐项核对保持一致），${otherN}个已知起点不是${otherN*3}个独立样本。保留全部重复；深入继承旧版限时路径的对照不得选取最差单次。这个小样本仅用于回归，不能证明其他模式整体棋力变强。各模式未改评价权重/搜索深度，深入保留 V11.6 拥挤盘高速核心 d5。`,''];
 for(const mode of ['fast','strong','extreme']){const vs=['v11.6-'+mode,'current-'+mode],a=other.rows.filter(r=>vs.includes(r.variant));lines.push('### '+mode,'',metricTable(a,vs),'',repeatedTable(a,vs),'',`配对新增步数胜/负/平：${Object.values(paired(a,vs[1],vs[0])).join('/')}。`,'');}
 lines.push('## 固定棋盘性能','',
 '性能单独运行，预热20局面、四个计算Worker，固定同一组棋盘、交替A/B五遍。没有同时运行其他CPU密集基准。记录每个请求的完整分数、深度与方向。compute 是每轮最长计算通道之和及 verifier/风险任务（风险任务已含证明）；协调器耗时和调用端往返耗时分开记录。表中端到端指Node调用端发出请求到收到答复，不含浏览器DOM绘制和用户走棋间隔，不能当作macOS原生浏览器测量。完整轮次包含被弃置的计算。每次测量立即追加原始请求日志，每遍保存完整中间报告，避免执行中断丢失测量；未完成数据保持未完成标记。整局平均耗时不用于声称加速。','',
 table(['同策略比较','评分/深度/方向一致','计算中位数/P95 旧→新','协调器中位数/P95 旧→新','端到端中位数/P95 旧→新','达到提速门槛'],Object.entries(lat.summary).map(([label,s])=>{const a=s.latency['v11.6'],b=s.latency.current;return [label,`${s.sameScores}/${s.samples} · ${s.sameDepths}/${s.samples} · ${s.sameMoves}/${s.samples}`,`${n(a.computeMs.median)}/${n(a.computeMs.p95)}→${n(b.computeMs.median)}/${n(b.computeMs.p95)}`,`${n(a.coordinatorMs.median)}/${n(a.coordinatorMs.p95)}→${n(b.coordinatorMs.median)}/${n(b.coordinatorMs.p95)}`,`${n(a.wallMs.median)}/${n(a.wallMs.p95)}→${n(b.wallMs.median)}/${n(b.wallMs.p95)}`,String(s.clearSpeedup)];})),'',
 '同策略神级分别对齐 V11.6 神级选项和稳定策略（V11.6 极致）。最终神级策略保持原样；候选策略的失败独立于开销优化。只有评分、深度、实际出招完全一致且中位数减少至少5%、P95不增加超过5%时才声称明确提速；其他模式只能报告观测值或持平。预算路径出现不同结果时原始差异全部保存，不能称为严格决策不变。','');
 const ls=lat.summary.strong.latency;lines.push(`固定棋盘旧 V11.5 深入也做了全部五遍：协调器均值 ${n(ls['v11.5'].coordinatorMs.mean)} ms，V11.6 ${n(ls['v11.6'].coordinatorMs.mean)} ms，V11.7 ${n(ls.current.coordinatorMs.mean)} ms；V11.7 相对旧深入 ${pc(1-ls.current.coordinatorMs.mean/ls['v11.5'].coordinatorMs.mean)}。这是本轮测量，不能直接照抄历史57%。`,'',
 '### 打包消息独立消融','',table(['同策略','原棋盘消息端到端中位数/P95','打包消息端到端中位数/P95','评分/深度/出招均相同'],Object.entries(lat.summary).map(([k,s])=>[k,`${n(s.transportAblation.boardMessages.wallMs.median)}/${n(s.transportAblation.boardMessages.wallMs.p95)}`,`${n(s.transportAblation.packedMessages.wallMs.median)}/${n(s.transportAblation.packedMessages.wallMs.p95)}`,String(s.transportAblation.identicalDecisions)])),'','这项消融仅替换同一新源码的价值任务消息形式，其他开销优化和策略完全相同；使用两个独立预热池，交替A/B五遍，避免结果缓存与固定先后顺序偏差。Worker仍校验词范围、深度与总量；缓存和合法根评分语义不改。','', '## 正确性、复现与交付边界','',
 `${tests.groups} 组 / ${tests.tests} 项回归通过。完整逐步回放校验 ${replay.records} 局、${n(replay.moves)} 个移动，出生格/值、随机数状态、分数、累计步数、质量和势能恒等式及最终无合法动作全部通过。`,'',
 '原神级规则及 WASM d3–d6 与宽位/视野保护、未完成搜索/概率不得参与、全部合法根、取消/缓存隔离、旧存档及浏览器键、导入导出/撤销/自动玩均保留。HTML 与当前规则/协调器/worker 和两份外部WASM逐字节核对。Mac .command/.sh 可执行并通过语法检查；实际测试环境为Node/Linux，DOM模拟与真实计算线程，未声称macOS原生浏览器实测。离线HTML不需要联网。','',
 '最终20局使用的准确HTML保存为 tests/fixtures/v117-release-engine.html。随后只修正页面与UI措辞；最终HTML的规则、协调器、Worker和内嵌WASM与该冻结文件逐字节一致，V11_7_FINAL_BUILD_IDENTITY.json记录两份HTML及引擎散列。固定棋盘性能使用最终HTML。','',
 '浏览器导入只恢复棋盤/分数/总步数，继续使用浏览器随机数；严格同流复测由命令行PRNG恢复执行，两者不能混同。每局JSONL.gz日志记录所有实际出招和出生，重放脚本可以核查。生成器保留来源散列及从空盘真实对局的出生证书；阶段HTML冻结文件是历史实验的准确复现入口。','',
 '```sh','npm run build','npm test','npm run replay:v117','CURRENT_HTML=tests/fixtures/v117-development.html npm run benchmark:v117:dev','npm run benchmark:v117:retain5','CURRENT_HTML=tests/fixtures/v117-validation.html VARIANTS=rawNoMerge OUTPUT=docs/merge-rerun.json npm run benchmark:v117:dev','npm run benchmark:v117','npm run benchmark:v117:other','npm run benchmark:v117:latency','```','',
 '复测默认生成新的报告文件与日志，不覆盖本轮原始记录。中断后仅显式 RESUME=1 且策略散列、选项和起点散列一致才能跳过已完成记录。实验生成器禁止覆盖冻结验证集合。原始8局生成工具仍属于历史工具，若使用应写入独立目录，不能覆盖本轮新集合。','',
 `最终HTML SHA256：\`${result.currentHTMLSHA256}\`。输入历史散列和所有最终文件散列见 MANIFEST。汇总为 V11_7_SUMMARY.json，验收结果为 V11_7_RELEASE_DECISION.json。`,'');
 fs.writeFileSync(root+'/docs/V11_7_UPGRADE.md',lines.join('\n'));
 const speeds=Object.entries(lat.summary).filter(([,s])=>s.clearSpeedup).map(([k])=>k);
 fs.writeFileSync(root+'/README.md',`# 2048 AI V11.7\n\n双击“启动 2048 AI.command”，或直接打开 2048-ai.html。离线、本机计算，无需账号或联网；停止服务用“停止本地服务.command”。Mac端口20480。\n\n${gate.passed?`神级采用通过独立终局验收的 ${candidate} 候选。`:'神级维持输入 V11.6 原策略，所有新候选未通过验收，不能称为神级棋力升级。'} 深入保留 V11.6 拥挤盘高速 d5。代码减少部分重复打包和临时分配，但本轮没有模式通过明确提速门槛；构建同步两份 WASM。旧稳定基线的回退在新集合上也有严重反例，因此该回退撤销。此处理偏离原先回退预案，完整说明见报告；候选验收门槛保持原样。本版没有完成神级高分存活全面升级目标。\n\n本轮：64个前期开发终局、8个验证失败后的追加消融终局，20个新真实高分起点×3策略×2重复，其他三模式${otherN}起点×同名A/B×3重复，最终默认20局复核。完整逐局/退步/验收/性能见 [升级报告](docs/V11_7_UPGRADE.md)。明确提速门槛通过：${speeds.join('、')||'无（不能宣称明确提速）'}。\n\n## 高分存档\n\n导入 tests/fixtures/late-game-v117/ 中的20份JSON，恢复棋盘、分数、累计步数。16份约17万分、4份约23万分。旧8份全是开发样本。浏览器导入后使用浏览器随机数；命令行才能严格恢复完整PRNG流。旧格式/浏览器存储键/导出/撤销/自动玩继续兼容，导出名为2048-v11.7-。直接打开HTML与本地服务使用不同浏览器存储来源。\n\n## 复测\n\n需要Node.js，无需npm install。不要同时运行多个CPU基准。\n\n\`\`\`sh\nnpm run build\nnpm test\nnpm run replay:v117\nnpm run benchmark:v117:retain5\nCURRENT_HTML=tests/fixtures/v117-development.html npm run benchmark:v117:dev\nCURRENT_HTML=tests/fixtures/v117-validation.html VARIANTS=rawNoMerge OUTPUT=docs/merge-rerun.json npm run benchmark:v117:dev\nnpm run benchmark:v117\nnpm run benchmark:v117:other\nnpm run benchmark:v117:latency\n\`\`\`\n\n复测另写带时间戳的文件；仅显式RESUME=1可恢复匹配策略/随机流的中断报告。默认神级策略以最终HTML为准，实验复现使用冻结HTML及白名单布尔开关。验证集合不得用来继续调参；要调参必须换新独立集合。\n\n全部${tests.tests}项回归通过，逐步回放${replay.records}局全部终局校验通过。测试环境Node/Linux，含DOM模拟与真实Worker；Mac脚本仅做权限/语法验证。架构与边界见docs/ARCHITECTURE.md。本轮文档是V11_7_*，V11_6_*及更旧文件均为历史证据。\n`);
 console.log(JSON.stringify({goalMet:gate.passed,HTML:result.currentHTMLSHA256,tests:tests.tests,speeds}));
})().catch(e=>{console.error(e);process.exitCode=1;});
